config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root 'top#index'
  get '/timeline', to:'articles#timeline'
  get '/favorites', to: 'articles#favorites'


  resources :articles do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resource :stocks, only: [:create, :destroy]
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    member do
    get :follows
    get :followers
    get :stocks
    get :favorites
  end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  layout 'top'

  def index
  end

end

app/views/top/index.html.slim
.wrapper
  .bg-mask
    .container.mx-auto
      .text-box.text-center
        h1.top_text.font-weight-bold
          | Fire ノート
        br
        p.top_text.font-weight-bold
          | 経験をかたちにする。
      .btn-box.text-center.d-flex.flex-column
        div = link_to 'ログイン', "/users/sign_in", class: 'btn btn-danger w-25 my-2'
        div = link_to '新規登録', "/users/sign_up", class: 'btn btn-danger w-25 my-2'
        div = link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post, class: 'btn btn-warning w-25 my-2'

.container
  .middle-wrapper
    .middle-wrapper-label.text-center.py-5.my-5
      h1.font-weight-bold.text-danger 何ができるか？
    .middle-wrapper-content.d-flex.justify-content-between
      .content-left.bg-light
        .article-post
          h2.font-weight-bold.text-center.py-4 記事の投稿
        .text-center
          = image_tag 'post.png', :size => '150x150', class: 'my-5'
        h5.p-4 自身が経験したことを記事にして、ふりかえることができます。効率的にふりかえりをすることができるように記事のフォーマットはKPT方式を採用しました。
      .content-center.bg-light
        h2.font-weight-bold.text-center.py-4 ストック・お気に入り
        .text-center
          = image_tag 'stock.png', :size => '150x150', class: 'my-5'
          = image_tag 'favorite.png', :size => '50x50', class: 'my-5'
        h5.p-4 あとで見返したい記事をストックしたり、お気に入りの記事にいいねをすることができます。
      .content-right.bg-light
        h2.font-weight-bold.text-center.py-4 フォロー
        .text-center
          = image_tag 'follow.png', :size => '150x150', class: 'my-5'
        h5.p-4 チェックしておきたいユーザーをフォローすることができ、フォローしたユーザーのタイムラインを見ることができます。




.footer.bg-light.text-danger
  .container
    .footer-label.mt-5
      h2.font-weight-bold  FIRE ノート
      p.mb-0 Copyright (c)  All Rights Reserved