config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root 'top#index'
  get '/timeline', to:'articles#timeline'
  get '/favorites', to: 'articles#favorites'


  resources :articles do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resource :stocks, only: [:create, :destroy]
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    member do
    get :follows
    get :followers
    get :stocks
    get :favorites
  end
  end
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many :stocks, dependent: :destroy
  has_many :comments, dependent: :destroy

  #記事がファボしてあるかどうかの判定
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  #記事がストックしてあるかどうかの判定
  def stocked_by?(user)
    stocks.where(user: user).exists?
  end

  validates :title, presence: true, length: { maximum: 48 }
  validates :kind, presence: true
  validates :summary, presence: true
  validates :content, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :sign_in_required, only: [:index]
  before_action :authenticate_user!

  def timeline
    if user_signed_in?
      @feed_items = current_user.feed.order("created_at DESC").page(params[:page]).per(20)
    end
  end

  def index
    @q = Article.ransack(params[:q])
    @articles = @q.result(distinct: true).order("created_at DESC").page(params[:page]).per(20)
  end

  def favorites
    # @all_ranks = Article.where(id: Favorite.group(:article_id).order(Arel.sql('count(article_id) desc')).pluck(:article_id)).page(params[:page]).per(20)
    @all_ranks = Favorite.includes(article: :user).group(:article_id).order(Arel.sql('count desc')).select('article_id, count(article_id) as count').page(params[:page]).per(20)
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments
    @comment = Comment.new
  end

  def new
    @article = current_user.articles.build
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      redirect_to article_path(@article), notice: "記事を投稿しました！"
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article), notice: "記事を更新しました！"
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      redirect_to articles_path, notice: "記事を削除しました！"
    else
      render :show
    end
  end

  private
    def article_params
      params.require(:article).permit(:title, :kind, :summary, :content, :good_point, :problem, :challenge)
    end
end

app/views/articles/_favorite_action.html.slim
- if user_signed_in?
  - if article.favorited_by?(current_user)
    p.mb-0 = link_to icon('fas', 'heart'), article_favorites_path(article.id), method: :delete, remote: true, class: 'heart-icon '
    .favorite-count.text-center.pb-3
      = article.favorites.count
  - else
    p.mb-0 = link_to icon('fas', 'heart-broken'),article_favorites_path(article.id), method: :post, remote: true, class: 'heart-broken-icon'
    .favorite-count.text-center.pb-3
      = article.favorites.count
- else
  p
    span お気に入り数:
    = article.favorites.count

app/views/articles/_stock_action.html.slim
- if user_signed_in?
  - if article.stocked_by?(current_user)
    p = link_to icon('fas', 'clipboard-check'), article_stocks_path(article.id), method: :delete, remote: true, class: 'clipboard-check-icon'
  - else
    p = link_to icon('fas', 'clipboard'), article_stocks_path(article.id), method: :post, remote: true, class: 'clipboard-icon'
- else
  p
    span ストック数:
    = article.stocks.count

app/views/articles/edit.html.slim
= form_with model: @article, local: true do |f|
  = render 'layouts/error_messages', model: f.object
  .form
    .form-group
      = f.label "タイトル", class: 'font-weight-bold'
      .badge.badge-danger.ml-2 必須
      = f.text_field :title, class: 'form-control'
    .form-group
      = f.label "種別", class: 'font-weight-bold'
      .badge.badge-danger.ml-2 必須
      br
      = f.select :kind, [["火災", "火災"], ["警戒", "警戒"], ["救急", "救急"], ["救助", "救助"], ["その他", "その他"]],
      include_blank: "選択して下さい"
    .form-group
      = f.label "概要", class: 'font-weight-bold'
      .badge.badge-danger.ml-2 必須
      = f.text_area :summary, rows: 3, class: 'form-control'
    .form-group
      = f.label "活動内容", class: 'font-weight-bold'
      .badge.badge-danger.ml-2 必須
      = f.text_area :content, rows: 5, class: 'form-control'
    .form-group
      = f.label "Keep(良かったこと)", class: 'font-weight-bold'
      = f.text_area :good_point, rows: 5, class: 'form-control'
    .form-group
      = f.label "Ploblem(悪かったこと)", class: 'font-weight-bold'
      = f.text_area :problem, rows: 5, class: 'form-control'
    .form-group
      = f.label "Try(次にやること)", class: 'font-weight-bold'
      = f.text_area :challenge, rows: 5, class: 'form-control'
  .post-btn.text-center
    =f.submit "更新する", class: 'btn btn-danger text-white font-weight-bold border w-25'

app/views/articles/favorites.html.slim
.follow.d-flex.justify-content-start
  .user-info.rounded.sticky-top
    .user-info-image.text-center.my-3
      = image_tag current_user.avatar.thumb.url, :size => '60x60', class: 'rounded'
    .user-info-name.text-center
      = link_to current_user.name, "/users/#{current_user.id}",class: 'text-dark font-weight-bold'
    .user-info-article.py-3.text-center
      p.my-0.text-dark.font-weight-bold 記事数
      = current_user.articles.count
    .user-info-following.py-3.text-center
      p.my-0 = link_to "フォロー", follows_user_path(current_user.id), class: 'text-dark font-weight-bold'
      = current_user.followings.count
    .user-info-follower.py-3.text-center
      p.my-0 = link_to "フォロワー", followers_user_path(current_user.id), class: 'text-dark font-weight-bold'
      = current_user.followers.count
    .user-info-timeline.text-center.py-3
        = link_to 'タイムラインをみる', timeline_path, class: 'btn btn-danger text-white w-75'
    .user-info-edit.text-center.py-3
      = link_to 'プロフィール編集', edit_user_registration_path, class: 'btn btn-danger text-white w-75'


  .bg-white.py-3.px-3.w-75.rounded
    ul.nav.nav-tabs
      li.nav-item
        = link_to '記事一覧', articles_path, class: 'text-dark font-weight-bold nav-link'
      li.nav-item
        a.nav-link.text-dark.font-weight-bold.active data-toggle="tab" href="#favorite_rank_articles"  いいね順

    .tab-content.py-4
      #favorite_rank_articles.tab-pane.active
        - if @all_ranks.present?
          - @all_ranks.each do |favorite|
            - article = favorite.article
            hr
            .top-article-section.d-flex.justify-content-between
              .top-article-section-left.ml-3.mb-0.d-flex.justify-content-start
                p.mt-3 = image_tag article.user.avatar.thumb.url, class: 'navigation__icon rounded'
                .contributor.pt-3.pl-3
                  p.mb-0 = link_to article.title, article_path(article), class: 'text-dark font-weight-bold'
                  p.mb-0.font-weight-light.text-secondary
                    span 投稿者：
                    = link_to article.user.name, user_path(article.user), class: 'text-secondary'
              .favorite-mark-count.pt-2.pr-2
                .favorite-mark.text-danger
                  = icon('fas', 'heart')
                .favorite-count.text-center
                  = favorite.count
          hr
        - else
          p 記事がありません。
        .pagi
          = paginate @all_ranks

app/views/articles/index.html.slim
.follow.d-flex.justify-content-start
  .user-info.rounded.sticky-top
    .user-info-image.text-center.my-3
      = image_tag current_user.avatar.thumb.url, :size => '60x60', class: 'rounded'
    .user-info-name.text-center
      = link_to current_user.name, "/users/#{current_user.id}",class: 'text-dark font-weight-bold'
    .user-info-article.py-3.text-center
      p.my-0.text-dark.font-weight-bold 記事数
      = current_user.articles.count
    .user-info-following.py-3.text-center
      p.my-0 = link_to "フォロー", follows_user_path(current_user.id), class: 'text-dark font-weight-bold'
      = current_user.followings.count
    .user-info-follower.py-3.text-center
      p.my-0 = link_to "フォロワー", followers_user_path(current_user.id), class: 'text-dark font-weight-bold'
      = current_user.followers.count
    .user-info-timeline.text-center.py-3
        = link_to 'タイムラインをみる', timeline_path, class: 'btn btn-danger text-white w-75'
    .user-info-edit.text-center.py-3
      = link_to 'プロフィール編集', edit_user_registration_path, class: 'btn btn-danger text-white w-75'

  .bg-white.py-3.px-3.w-75.rounded
    ul.nav.nav-tabs
      li.nav-item
        a.nav-link.text-dark.font-weight-bold.active data-toggle="tab" href="#articles"  記事一覧
      li.nav-item
        = link_to 'いいね順', favorites_path, class: 'text-dark font-weight-bold nav-link'

    .tab-content.py-4
      #articles.tab-pane.active
        - if @articles.present?
          - @articles.each do |article|
            hr
            .top-article-section.d-flex.justify-content-between
              .top-article-section-left.ml-3.mb-0.d-flex.justify-content-start
                p.mt-3 = image_tag article.user.avatar.thumb.url, class: 'navigation__icon rounded'
                .contributor.pt-3.pl-3
                  p.mb-0 = link_to article.title, article_path(article), class: 'text-dark font-weight-bold'
                  p.mb-0.font-weight-light.text-secondary
                    span 投稿者：
                    = link_to article.user.name, user_path(article.user), class: 'text-secondary'
              .favorite-mark-count.pt-2.pr-2
                .favorite-mark.text-danger
                  = icon('fas', 'heart')
                .favorite-count.text-center
                  = article.favorites.count
          hr
        - else
          p 記事がありません。
        .pagi
          = paginate @articles

app/views/articles/new.html.slim
= form_with model: @article, local: true do |f|
  = render 'layouts/error_messages', model: f.object
  .form
    .form-group
      = f.label "タイトル", class: 'font-weight-bold'
      .badge.badge-danger.ml-2 必須
      = f.text_field :title, class: 'form-control'
    .form-group
      = f.label "種別", class: 'font-weight-bold'
      .badge.badge-danger.ml-2 必須
      br
      = f.select :kind, [["火災", "火災"], ["警戒", "警戒"], ["救急", "救急"], ["救助", "救助"], ["その他", "その他"]],
      {include_blank: "選択して下さい"}, {class: 'form-control select-box'}
    .form-group
      = f.label "概要", class: 'font-weight-bold'
      .badge.badge-danger.ml-2 必須
      = f.text_area :summary, rows: 3, class: 'form-control'
    .form-group
      = f.label "活動内容", class: 'font-weight-bold'
      .badge.badge-danger.ml-2 必須
      = f.text_area :content, rows: 5, class: 'form-control'
    .form-group
      = f.label "Keep(良かったこと)", class: 'font-weight-bold'
      = f.text_area :good_point, rows: 5, class: 'form-control'
    .form-group
      = f.label "Ploblem(悪かったこと)", class: 'font-weight-bold'
      = f.text_area :problem, rows: 5, class: 'form-control'
    .form-group
      = f.label "Try(次にやること)", class: 'font-weight-bold'
      = f.text_area :challenge, rows: 5, class: 'form-control'
  .post-btn.text-center
    =f.submit "投稿する", class: 'btn btn-danger text-white font-weight-bold border w-25'

app/views/articles/show.html.slim
.article-show.d-flex.justify-content-start
  .icons.ml-5.sticky-top
    #favorite_buttons
      = render 'favorite_action', article: @article

    #stock_buttons.text-center
      = render 'stock_action', article: @article

  .article-content.bg-white.px-3.py-3.ml-5.w-75.rounded.border
    = link_to user_path(@article.user) do
      = image_tag @article.user.avatar.thumb.url, class: 'navigation__icon mr-3 rounded'
      = link_to @article.user.name, user_path(@article.user), class: 'text-dark'
    .edit-delete.text-right
      - if @article.user == current_user
        = link_to icon('fas', 'pencil-alt', '編集する'), edit_article_path(@article), class: 'pencil-alt-icon mx-2'
        = link_to icon('fas', 'trash-alt', '削除する'), article_path(@article), method: :delete,
                                                        data: { confirm: "削除してもよろしいですか？" }, class: 'trash-alt-icon mx-2'
    .contents.py-3
      h2 = @article.title
      p.text-secondary.text-right
        span 種別：
        = @article.kind
      h4.mb-0 概要
      hr.my-0
      .text-wrap.pt-1.pb-3
        = simple_format(@article.summary)
      h4 活動内容
      hr.my-0
      .text-wrap.pt-1.pb-3
        = simple_format(@article.content)

    - if @article.good_point.present?
      h4 Keep
      hr.my-0
      .text-wrap.pt-1.pb-3
        = simple_format(@article.good_point)
    - if @article.problem.present?
      h4 Ploblem
      hr.my-0
      .text-wrap.pt-1.pb-3
        = simple_format(@article.problem)
    - if @article.challenge.present?
      h4 Try
      hr.my-0
      .text-wrap.pt-1.pb-3
        = simple_format(@article.challenge)

    .comments
      h4.mb-4 コメント
      - @comments.each do |c|
        .comment-up-content.d-flex.justify-content-between
          .left-side
            = image_tag c.user.avatar.thumb.url, class: 'navigation__icon mr-3 rounded'
            = link_to c.user.name, user_path(c.user), class: 'text-dark'
          - if c.user == current_user
            .right-side
              = link_to icon('fas', 'trash-alt', '削除する'), article_comment_path(c.article.id, c.id), method: :delete, class: 'text-dark'
        .comment-down-content.pt-3
          = simple_format(c.body)
          hr
      = form_for [@article, @comment] do |f|
        = f.text_area :body, rows: 3, class: 'form-control'
        br
        .text-right
          = f.submit 'コメントする', class: 'btn btn-danger text-white'

app/views/articles/timeline.html.slim
.timeline-list.bg-white.px-3.py-3.mx-auto.w-75.rounded
  .text-dark.font-weight-bold
    p.ml-3 タイムライン
  - if @feed_items.present?
    - @feed_items.each do |feed_item|
      hr
      .timeline-section.d-flex.justify-content-between
        .timeline-section-left.pt-3.pl-3
          .div.d-flex.flex-row
            div = image_tag feed_item.user.avatar.thumb.url, class: 'navigation__icon rounded'
            .div.ml-4
              p.mb-0.font-weight-light.text-secondary
                = link_to feed_item.user.name, user_path(feed_item.user), class: 'text-secondary'
                span さんが記事を投稿しました。
              p.mb-0 = link_to feed_item.title, article_path(feed_item), class: 'text-dark font-weight-bold'
        .timeline-section-time.pt-3
          = l feed_item.created_at, format: :short
    hr
  - else
    p タイムラインがありません。
  .pagi.pt-3
    = paginate @feed_items

.timeline-to-mypage.text-center.pt-4
  = link_to 'マイページへ戻る', "/users/#{current_user.id}", class: 'btn btn-danger'