config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  root 'top#index'
  get '/timeline', to:'articles#timeline'
  get '/favorites', to: 'articles#favorites'


  resources :articles do
    resource :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    resource :stocks, only: [:create, :destroy]
  end

  resources :users do
    resource :relationships, only: [:create, :destroy]
    member do
    get :follows
    get :followers
    get :stocks
    get :favorites
  end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  mount_uploader :avatar, AvatarUploader

  has_many :articles, dependent: :destroy
  has_many :favorites
  has_many :favorite_articles, through: :favorites, source: :article
  has_many :stocks
  has_many :stock_articles, through: :stocks, source: :article
  has_many :comments

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower

  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def feed
    # following_ids = "SELECT follower_id FROM relationships
    #                 WHERE following_id = :user_id"
    # Article.where("user_id IN (#{following_ids})
    #                 OR user_id = :user_id", user_id: id)

    Article.where(user: active_relationships.select(:follower_id)).or(articles)
  end

  def self.guest
    find_or_create_by!(name: 'テストファイヤーマン', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  validates :name, presence: true, length: { maximum: 10 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  layout 'unauthorized'
  before_action :check_guest, only: %i[update destroy]

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to articles_path, alert: 'ゲストユーザーの編集・削除できません。'
    end
  end

  #アカウント更新後の遷移先を指定
  protected

    def after_update_path_for(resource)
      user_path(resource)
    end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout 'unauthorized'

  def new_guest
    user = User.guest
    sign_in user
    redirect_to articles_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show stocks favoites edit follows followers]

  def index
    @users = User.all.order(created_at: :desc).page(params[:page]).per(20)
  end

  def show
    @articles = @user.articles.order("created_at DESC").page(params[:page]).per(20)
    # @favorite_articles = @user.favorite_articles.order("created_at DESC").page(params[:page]).per(20)
    # @stock_articles = @user.stock_articles.order("created_at DESC").page(params[:page]).per(20)
  end

  def stocks
    @articles = @user.articles.order("created_at DESC").page(params[:page]).per(20)
    @stock_articles = @user.stock_articles.order("created_at DESC").page(params[:page]).per(20)
  end

  def favorites
    @articles = @user.articles.order("created_at DESC").page(params[:page]).per(20)
    @favorite_articles = @user.favorite_articles.order("created_at DESC").page(params[:page]).per(20)
  end

  def edit; end

  def update
    if @user.update
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def follows
    @users = @user.followings.page(params[:page]).per(200)
  end

  def followers
    @users = @user.followers.page(params[:page]).per(200)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

end

app/views/users/_follow_action.html.slim
- if current_user != user
    - if user.followed_by?(current_user)
      p= link_to "フォロー解除", user_relationships_path(user.id), method: :delete, remote: true, class: 'btn btn-secondary'
    - else
      p= link_to "フォローする", user_relationships_path(user.id), method: :post, remote: true, class: 'btn btn-danger'

app/views/users/favorites.html.slim
.user-show-page.d-flex.justify-content-start
  .user-info.rounded.sticky-top
    .user-info-image.text-center.my-3
      = image_tag @user.avatar.thumb.url, :size => '60x60', class: 'rounded'
    .user-info-name.text-center.text-dark.font-weight-bold
      = @user.name
    .user-info-article.py-3.text-center
      p.my-0.text-dark.font-weight-bold 記事数
      = @user.articles.count
    .user-info-following.py-3.text-center
      p.my-0 = link_to "フォロー", follows_user_path(@user.id), class: 'text-dark font-weight-bold'
      = @user.followings.count
    .user-info-follower.py-3.text-center
      p.my-0 = link_to "フォロワー", followers_user_path(@user.id), class: 'text-dark font-weight-bold'
      = @user.followers.count
    - if current_user.id == @user.id
      .user-info-edit.text-center.py-3
        = link_to 'タイムライン', timeline_path,class: 'btn btn-danger w-75'
      .user-info-edit.text-center.py-3
        = link_to 'プロフィール編集', edit_user_registration_path,class: 'btn btn-danger w-75'
    - else
      #follow_button.text-center.pt-5
        = render 'follow_action', user: @user

  .bg-white.py-3.px-3.w-75.rounded
    - if current_user.id == @user.id
      ul.nav.nav-tabs
        li.nav-item
          = link_to 'あなたの記事', user_path, class: 'text-dark font-weight-bold nav-link'
        li.nav-item
          = link_to 'ストック一覧', stocks_user_path, class: 'text-dark font-weight-bold nav-link'
        li.nav-item
          a.nav-link.text-dark.font-weight-bold.active data-toggle="tab" href="#favorite_articles"  お気に入り記事

      .tab-content.py-4
        #favorite_articles.tab-pane.active
          - if @favorite_articles.present?
            - @favorite_articles.each do |article|
              hr
              .top-article-section.d-flex.justify-content-between
                .top-article-section-left.ml-3.mb-0.d-flex.justify-content-start
                  p.mt-3 = image_tag article.user.avatar.thumb.url, class: 'navigation__icon rounded'
                  .contributor.pt-3.pl-3
                    p.mb-0 = link_to article.title, article_path(article), class: 'text-dark font-weight-bold'
                    p.mb-0.font-weight-light.text-secondary
                      span 投稿者：
                      = link_to article.user.name, user_path(article.user), class: 'text-secondary'
                .favorite-mark-count.pt-2.pr-2
                  .favorite-mark.text-danger
                    = icon('fas', 'heart')
                  .favorite-count.text-center
                    = article.favorites.count
            hr
          - else
            p 記事がありません。
          .pagi
            = paginate @favorite_articles

    - else
      p.font-weight-bold
        = @user.name
        span さんの記事
      hr
      - if @articles.present?
        - @articles.each do |article|
          hr
          .d-flex.justify-content-between
            .article-title-only.pt-3.pl-2
              = link_to article.title, article_path(article.id), class: 'text-dark font-weight-bold'
            .favorite-mark-count.pr-2
              .favorite-mark.text-danger
                = icon('fas', 'heart')
              .favorite-count.text-center
                = article.favorites.count
      - else
        p 記事がありません。
      .pagi
        = paginate @articles

app/views/users/followers.html.slim
.follow.d-flex.justify-content-around
  .user-info.rounded.sticky-top
    .user-info-image.text-center.my-3
      = image_tag @user.avatar.thumb.url, :size => '60x60', class: 'rounded'
    .user-info-name.text-center
      = link_to @user.name, "/users/#{@user.id}",class: 'text-dark font-weight-bold'
    .user-info-article.py-3.text-center
      p.my-0.text-dark.font-weight-bold 記事数
      = @user.articles.count
    .user-info-following.py-3.text-center
      p.my-0 = link_to "フォロー", follows_user_path(@user.id), class: 'text-dark font-weight-bold'
      = @user.followings.count
    .user-info-follower.py-3.text-center
      p.my-0 = link_to "フォロワー", followers_user_path(@user.id), class: 'text-dark font-weight-bold'
      = @user.followers.count
    - if current_user.id == @user.id
      .user-info-edit.text-center.py-3
        = link_to 'ユーザー情報編集', edit_user_registration_path,class: 'btn btn-danger w-75'
    - else
      #follow_button.text-center.pt-5
        = render 'follow_action', user: @user

  .follow-list.bg-white.py-3.px-3.rounded.w-75
    h4 フォロワー
    - if @users.present?
      - @users.each do |user|
        hr
        .follow-list-section.my-3.d-flex.justify-content-between.align-items-center
          .avator-and-name.d-flex.justify-content-start
            .circle-avatar.ml-3
              = image_tag user.avatar.thumb.url, class: 'rounded'
            .follow-info.ml-3
              .follow-info-name.mt-4
                = link_to user.name, user_path(user.id), class: 'text-dark'
              .follow-info-article.text-secondary
                span 記事投稿数:
                = user.articles.count
          .follow-btn
            div id="follow_button_#{user.id}"
              = render 'follow_action', user: user
      hr
    - else
      p フォローされていません。
    .pagi
        = paginate @users

app/views/users/follows.html.slim
.follow.d-flex.justify-content-around
  .user-info.rounded.sticky-top
    .user-info-image.text-center.my-3
      = image_tag @user.avatar.thumb.url, :size => '60x60', class: 'rounded'
    .user-info-name.text-center
      = link_to @user.name, "/users/#{@user.id}",class: 'text-dark font-weight-bold'
    .user-info-article.py-3.text-center
      p.my-0.text-dark.font-weight-bold 記事数
      = @user.articles.count
    .user-info-following.py-3.text-center
      p.my-0 = link_to "フォロー", follows_user_path(@user.id), class: 'text-dark font-weight-bold'
      = @user.followings.count
    .user-info-follower.py-3.text-center
      p.my-0 = link_to "フォロワー", followers_user_path(@user.id), class: 'text-dark font-weight-bold'
      = @user.followers.count
    - if current_user.id == @user.id
      .user-info-edit.text-center.py-3
        = link_to 'ユーザー情報編集', edit_user_registration_path,class: 'btn btn-danger w-75'
    - else
      #follow_button.text-center.pt-5
        = render 'follow_action', user: @user

  .follow-list.bg-white.py-3.px-3.rounded.w-75
    h4 フォロー
    - if @users.present?
      - @users.each do |user|
        hr
        .follow-list-section.my-3.d-flex.justify-content-between.align-items-center
          .avator-and-name.d-flex.justify-content-start
            .circle-avatar.ml-3
              = image_tag user.avatar.thumb.url, class: 'rounded'
            .follow-info.ml-3
              .follow-info-name.mt-4
                = link_to user.name, user_path(user.id), class: 'text-dark'
              .follow-info-article.text-secondary
                span 記事投稿数:
                = user.articles.count
          .follow-btn
            div id="follow_button_#{user.id}"
              = render 'follow_action', user: user
      hr
    - else
      p フォローしているユーザーはいません。
    .pagi
        = paginate @users

app/views/users/index.html.slim
.users.d-flex.justify-content-around
  .user-info.rounded.sticky-top
    .user-info-image.text-center.my-3
      = image_tag current_user.avatar.thumb.url, :size => '60x60', class: 'rounded'
    .user-info-name.text-center
      = link_to current_user.name, "/users/#{current_user.id}",class: 'text-dark font-weight-bold'
    .user-info-article.my-5.text-center
      p.my-0.text-dark.font-weight-bold 記事数
      = current_user.articles.count
    .user-info-following.my-5.text-center
      p.my-0 = link_to "フォロー", follows_user_path(current_user.id), class: 'text-dark font-weight-bold'
      = current_user.followings.count
    .user-info-follower.my-5.text-center
      p.my-0 = link_to "フォロワー", followers_user_path(current_user.id), class: 'text-dark font-weight-bold'
      = current_user.followers.count
    .user-info-edit.my-5.text-center
      = link_to 'プロフィール編集', edit_user_registration_path,class: 'btn btn-danger w-75'

  .users-list.bg-white.py-3.px-3.rounded.w-75
    h4 すべてのユーザー
    - if @users.present?
      - @users.each do |user|
        hr
        .users-list-section.my-3.d-flex.justify-content-between.align-items-center
          .avator-and-name.d-flex.justify-content-start
            .circle-avatar.ml-3
              = image_tag user.avatar.thumb.url, class: 'rounded'
            .users-info.ml-3
              .users-info-name.mt-4
                = link_to user.name, user_path(user.id), class: 'text-dark'
              .users-info-article.text-secondary
                span 記事投稿数:
                = user.articles.count
          .users-btn
            div id="follow_button_#{user.id}"
              = render 'follow_action', user: user
      hr
    - else
      p ユーザーはいません。
    .pagi
      = paginate @users

app/views/users/show.html.slim
.user-show-page.d-flex.justify-content-start
  .user-info.rounded.sticky-top
    .user-info-image.text-center.my-3
      = image_tag @user.avatar.thumb.url, :size => '60x60', class: 'rounded'
    .user-info-name.text-center.text-dark.font-weight-bold
      = @user.name
    .user-info-article.py-3.text-center
      p.my-0.text-dark.font-weight-bold 記事数
      = @user.articles.count
    .user-info-following.py-3.text-center
      p.my-0 = link_to "フォロー", follows_user_path(@user.id), class: 'text-dark font-weight-bold'
      = @user.followings.count
    .user-info-follower.py-3.text-center
      p.my-0 = link_to "フォロワー", followers_user_path(@user.id), class: 'text-dark font-weight-bold'
      = @user.followers.count
    - if current_user.id == @user.id
      .user-info-edit.text-center.py-3
        = link_to 'タイムライン', timeline_path,class: 'btn btn-danger w-75'
      .user-info-edit.text-center.py-3
        = link_to 'プロフィール編集', edit_user_registration_path,class: 'btn btn-danger w-75'
    - else
      #follow_button.text-center.pt-5
        = render 'follow_action', user: @user

  .bg-white.py-3.px-3.w-75.rounded
    - if current_user.id == @user.id
      ul.nav.nav-tabs
        li.nav-item
          a.nav-link.text-dark.font-weight-bold.active data-toggle="tab" href="#your_articles"  あなたの記事
        li.nav-item
          = link_to 'ストック一覧', stocks_user_path, class: 'text-dark font-weight-bold nav-link'
        li.nav-item
          = link_to 'お気に入り一覧', favorites_user_path, class: 'text-dark font-weight-bold nav-link'

      .tab-content.py-4
        #your_articles.tab-pane.active
          - if @articles.present?
            - @articles.each do |article|
              hr
              .d-flex.justify-content-between
                .article-title-only.pt-3.pl-2
                  = link_to article.title, article_path(article.id), class: 'text-dark font-weight-bold'
                .favorite-mark-count.pr-2
                  .favorite-mark.text-danger
                    = icon('fas', 'heart')
                  .favorite-count.text-center
                    = article.favorites.count
            hr
          - else
            p 記事がありません。
          .pagi
            = paginate @articles
    - else
      p.font-weight-bold
        = @user.name
        span さんの記事
      hr
      - if @articles.present?
        - @articles.each do |article|
          hr
          .d-flex.justify-content-between
            .article-title-only.pt-3.pl-2
              = link_to article.title, article_path(article.id), class: 'text-dark font-weight-bold'
            .favorite-mark-count.pr-2
              .favorite-mark.text-danger
                = icon('fas', 'heart')
              .favorite-count.text-center
                = article.favorites.count
        hr
      -else
        p 記事がありません。
      .pagi
        = paginate @articles

app/views/users/stocks.html.slim
.user-show-page.d-flex.justify-content-start
  .user-info.rounded.sticky-top
    .user-info-image.text-center.my-3
      = image_tag @user.avatar.thumb.url, :size => '60x60', class: 'rounded'
    .user-info-name.text-center.text-dark.font-weight-bold
      = @user.name
    .user-info-article.py-3.text-center
      p.my-0.text-dark.font-weight-bold 記事数
      = @user.articles.count
    .user-info-following.py-3.text-center
      p.my-0 = link_to "フォロー", follows_user_path(@user.id), class: 'text-dark font-weight-bold'
      = @user.followings.count
    .user-info-follower.py-3.text-center
      p.my-0 = link_to "フォロワー", followers_user_path(@user.id), class: 'text-dark font-weight-bold'
      = @user.followers.count
    - if current_user.id == @user.id
      .user-info-edit.text-center.py-3
        = link_to 'タイムライン', timeline_path,class: 'btn btn-danger w-75'
      .user-info-edit.text-center.py-3
        = link_to 'プロフィール編集', edit_user_registration_path,class: 'btn btn-danger w-75'
    - else
      #follow_button.text-center.pt-5
        = render 'follow_action', user: @user

  .bg-white.py-3.px-3.w-75.rounded
    - if current_user.id == @user.id
      ul.nav.nav-tabs
        li.nav-item
          = link_to 'あなたの記事', user_path, class: 'text-dark font-weight-bold nav-link'
        li.nav-item
          a.nav-link.text-dark.font-weight-bold.active data-toggle="tab" href="#stock_articles"  ストック記事
        li.nav-item
          = link_to 'お気に入り一覧', favorites_user_path, class: 'text-dark font-weight-bold nav-link'

      .tab-content.py-4
        #stock_articles.tab-pane.active
          - if @stock_articles.present?
            - @stock_articles.each do |article|
              hr
              .top-article-section.d-flex.justify-content-between
                .top-article-section-left.ml-3.mb-0.d-flex.justify-content-start
                  p.mt-3 = image_tag article.user.avatar.thumb.url, class: 'navigation__icon rounded'
                  .contributor.pt-3.pl-3
                    p.mb-0 = link_to article.title, article_path(article), class: 'text-dark font-weight-bold'
                    p.mb-0.font-weight-light.text-secondary
                      span 投稿者：
                      = link_to article.user.name, user_path(article.user), class: 'text-secondary'
                .favorite-mark-count.pt-2.pr-2
                  .favorite-mark.text-danger
                    = icon('fas', 'heart')
                  .favorite-count.text-center
                    = article.favorites.count
            hr
          - else
            p 記事がありません。
          .pagi
            = paginate @stock_articles

    - else
      p.font-weight-bold
        = @user.name
        span さんの記事
      hr
      - if @articles.present?
        - @articles.each do |article|
          hr
          .d-flex.justify-content-between
            .article-title-only.pt-3.pl-2
              = link_to article.title, article_path(article.id), class: 'text-dark font-weight-bold'
            .favorite-mark-count.pr-2
              .favorite-mark.text-danger
                = icon('fas', 'heart')
              .favorite-count.text-center
                = article.favorites.count
      -else
        p 記事がありません。
      .pagi
        = paginate @articles